### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by feidasheng** [muzishen/Deepsort_V2#1]
您好作者，请问一下您的代码是对deepsort做了哪些改进，我最近也在研究mot部分的优化部分，希望能向你请教一下，谢谢

**Comment by muzishen** [comment]
这份代码关于deepsort部分，只是更新了一个蒸馏的reid模型，用的mobilenetv3。

**Comment by feidasheng** [comment]
在请问一下，您替换的这个reid部分在速度上面有了提升，reid部分精度有下降么？谢谢

**Comment by muzishen** [comment]
没有，这是我第一次做跟踪任务，但是我的调研和实验发现。跟踪任务检测是限制性能上限的因素，往往reid对于性能并没有很大帮助。
